package(default_visibility = ["//visibility:public"])

cc_library(
    name = "thread",
    srcs = ["threadpool.cc"],
    hdrs = ["barrier.h",
            "threadpool.h",],
    deps = ["//cpp-base",],
)
