package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hash",
    srcs = ["md5.cc",],
    hdrs = ["fingerprint2011.h",
            "hash.h",
            "md5.h",],
    deps = ["//cpp-base",],
)
