package(default_visibility = ["//visibility:public"])

cc_library(
    name = "file",
    srcs = ["file.cc",
            "filelinereader.cc"],
    hdrs = ["file.h",
            "filelineiter.h",
            "filelinereader.h"],
    deps = ["//cpp-base",
            "//cpp-base/string",],
)
