package(default_visibility = ["//visibility:public"])

cc_library(
    name = "file",
    srcs = ["file.cc",
            "file_input_stream.cc",
            "file_output_stream.cc",],
    hdrs = ["file.h",
            "file_input_stream.h",
            "file_output_stream.h",],
    deps = ["//cpp-base",
            "//cpp-base/string",],
)
